# Variables
# ---------
@baseUrl = http://{{$dotenv APP_ADDR}}:{{$dotenv APP_PORT}}/api/v1
@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVkQXQiOiIyMDIxLTA4LTI3VDE1OjIzOjMyLjIyNloiLCJleHAiOjE2NjM1MTY2MzIsImZpcnN0bmFtZSI6IlRvdG8gMiIsImlhdCI6MTY2MjY1MjYzMiwiaWQiOiJiNzg4ODkzZS02MWU2LTRhODQtOGRlYi0xZjhmNWFhNTYzMWUiLCJsYXN0bmFtZSI6IlRlc3QiLCJuYmYiOjE2NjI2NTI2MzIsInVzZXJuYW1lIjoidGVzdEBnbWFpbC5jb20ifQ._8aVrKnncADSaqB1eKQR8E1o3FWD6e7YnrqkgK1xEgyNbAd6G9oWr4SS_eboFZBwfx_WN4ztCJLsA13F2Pvg8g


# Users
# -----
@userId = b788893e-61e6-4a84-8deb-1f8f5aa5631e
@userIdToDelete = bf8cfc85-1554-4817-9674-96e5b8ddf5a7
@userEmail = test@gmail.com
@passwordResetToken = f419fee9-cae3-4e02-a0c6-55925640c4f2

# Login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "00000000"
}
###

# Forgotten password
POST {{baseUrl}}/forgotten-password/{{userEmail}}
Content-Type: application/json
###

# Update user password
PATCH {{baseUrl}}/update-password/{{passwordResetToken}}
Content-Type: application/json

{
    "password": "00000000"
}
###

# Register
POST {{baseUrl}}/register
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "test44@gmail.com",
    "password": "00000000",
    "lastname": "Test",
    "firstname": "Toto"
}
###

# Users list
GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{token}}
###

# User information
GET {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}
###

# Update user
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "test@gmail.com",
    "password": "00000000",
    "lastname": "Test",
    "firstname": "Toto 2"
}
###

# Delete user
DELETE {{baseUrl}}/users/{{userIdToDelete}}
Content-Type: application/json
Authorization: Bearer {{token}}
###


# Links
# -----

# Get all links
GET {{baseUrl}}/links?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{token}}
###

# Create new shortened URL
POST {{baseUrl}}/links
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "url": "https://google.com",
    "expired_at": "2024-12-31T00:00:00.222Z"
}
###
